config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: "secure"

  get "/home", to: "pages#home"
  get "/about", to: "pages#about"

  resources :entries

  root "entries#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user

  validates :name, :username, :password, presence: true
  validate :url_must_be_valid

  encrypts :username, deterministic: true # allows us to query against our username once encrypted
  encrypts :password

private

  def url_must_be_valid
    unless url.include?("http" || "https")
      errors.add(:url, "must be valid")
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :entries, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  allow_browser versions: :modern
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :authenticate_user!

  def index
    @entries = current_user.entries
  end

  def show
    @entry = current_user.entries.find(params[:id])
  end

  def new
    @entry = Entry.new
  end

  def create
    @entry = current_user.entries.new(entry_params)

    if @entry.save
      flash[:notice] = "Entry has been saved!"
      redirect_to root_path
    else
      flash[:alert] = "Sorry, there was an issue"
      render :new, status: :unprocessable_entity
    end
  end

private

  def entry_params
    params.expect(entry: [ :name, :url, :username, :password ])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home; end

  def about; end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def logo(size = "h2")
    link_to root_path, class: "logo #{size}" do
      "<i class=\"bi  bi-safe-fill me-2\"></i>DanPass".html_safe
    end
  end

  def account_page?
    current_page?(edit_user_registration_path)
  end
end

app/helpers/flash_helper.rb
module FlashHelper
  def flash_class(type)
    case type
    when "notice" then "success"
    when "alert" then "danger"
    end
  end
end

app/views/entries/_entry.html.erb
<div>
  <%= link_to(entry.name, entry_path(entry)) %>
</div>

app/views/entries/index.html.erb
<h1>Entries</h1>

<div class="row">
  <div class="card">
    <div class="card-body">
    <% if @entries.any? %>
      <%= render(@entries) %>
    <% else %>
      <h2>No entries yet. <%= link_to('Add an entry', new_entry_path) %></h2>
    <% end %>
    </div>
  </div>
</div>

app/views/entries/new.html.erb
<h1>New entry</h1>

<div class="row">
  <div class="col">
    <div class="card">
      <div class="card-body">
        <% if @entry.errors.any? %>
          <div id="error_explanation" class="alert alert-danger" role="alert">
            <h4>
              Please fix the <%= pluralize(@entry.errors.count, 'error') %> below and try again.
            </h4>
            <ul>
              <% @entry.errors.each do |e| %>
                <li><%= e.full_message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
        <%= form_with(model: @entry) do |f| %>
        <div class="form-floating mb-3">
          <%= f.text_field(:name, placeholder: 'Name', class: 'form-control') %>
          <%= f.label(:name) %>
        </div>
        <div class="form-floating mb-3">
          <%= f.text_field(:url, placeholder: 'URL', class: 'form-control') %>
          <%= f.label(:url) %>
        </div>
        <div class="form-floating mb-3">
          <%= f.text_field(:username, placeholder: 'Username', class: 'form-control') %>
          <%= f.label(:username) %>
        </div>
        <div class="form-floating mb-3">
          <%= f.text_field(:password, placeholder: 'Password', class: 'form-control') %>
          <%= f.label(:password) %>
        </div>
        <%= f.submit('Create new entry', class: 'btn btn-primary') %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/entries/show.html.erb
<h1><%= @entry.name %></h1>

<div>
  <%= @entry.url %>
</div>
<div>
  <%= @entry.username %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Dan Pass App" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>

  </head>

  <body>
    <%= render(partial: 'shared/navbar') %>
    <%= render(partial: 'shared/flash') %>

    <div class="container">
      <%= yield %>
    </div>
    
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "DanPass Secure Authentication" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body>
    <div class="vh-100">
      <%= render(partial: 'shared/flash') %>
      <%= render(partial: 'shared/navbar') if account_page? %>
      <div class="h-100 container d-flex flex-column justify-content-center align-items-center">
      <% unless account_page? %>
        <%= link_to(root_path, class: 'navbar-brand') do %>
          <%= logo %>
        <% end %>
      <% end %>
        <div class="card card--auth shadow-sm w-100">
          <div class="card-body">
            <%= yield %>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About</h1>

app/views/pages/home.html.erb
<h1>Hello world</h1>

app/views/shared/_flash.html.erb
<% flash.each do |type, message| %>
  <div class="toast align-items-center text-bg-<%= flash_class(type) %> border-0 position-absolute top-0 end-0 z-1 mt-5 me-5" role="alert" aria-live="assertive" aria-atomic="true" data-controller="toast">
    <div class="d-flex">
      <div class="toast-body">
        <%= message %>
      </div>
      <button type="button" class="btn-close btn-close-white me-2 m-auto" data-bs-dismiss="toast" aria-label="Close"></button>
    </div>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary border-bottom">
  <div class="container">
    <%= logo("h4") %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to('About', about_path, class: 'nav-link') %>
        </li>
        <li class="nav-item">
          <%= link_to('New entry', new_entry_path, class: 'nav-link ms-5') %>
        </li>
      </ul>
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
      <% if user_signed_in? %>
        <div class="dropdown">
          <button class="nav-link dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
            <i class="bi bi-person-circle"></i>
          </button>
          <ul class="dropdown-menu dropdown-menu-end">
            <li>
              <h6 class="dropdown-header">
                Signed in as:<br><%= current_user.email %>
              </h6>
            </li>
            <li>
              <%= link_to('Account', edit_user_registration_path, class: 'dropdown-item') %>
            </li>
            <li>
              <hr class="dropdown-divider">
            </li>
            <li> <%= link_to('Sign out', destroy_user_session_path, class: 'dropdown-item',
              data: { turbo_method: :delete }) %>
            </li>
          </ul>
        </div>
      <% else %>
        <li class="nav-item">
          <%= link_to('Sign in', new_user_session_path, class: 'nav-link') %>
        </li>
        <li class="nav-item">
          <%= link_to('Sign up', new_user_registration_path, class: 'nav-link') %>
        </li>
      <% end %>
      </ul>
    </div>
  </div>
</nav>